name: Reusable Deplyoment
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: Name of the artifact to download
        required: true
        default: dist-files
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
      - name: List files
        run: ls -l
      - name: Output information
        run: echo "Deploying & uploading artifacts"